name: Slither Analysis
on: 
  push
  pull_request
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive    
      - name: Set up Node
        uses: actions/setup-node@v3
      - uses: crytic/slither-action@v0.3.0
        with:
          target: 'voting-chain/'
          fail-on: none