name: Slither Analysis
on: push
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          target: 'voting-chain/'      
      - uses: crytic/slither-action@v0.3.0
        with:
          target: 'voting-chain/'